name: Lint and format

on:
  push:
    branches-ignore:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check
